// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoneBook.Persistence;

#nullable disable

namespace PhoneBook.Persistence.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250517200550_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoneBook.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleJob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c16487f1-6d0a-4ce1-bffa-13755b63cf60"),
                            BirthDate = new DateOnly(2004, 9, 26),
                            MobilePhone = "+375 (29) 123-45-67",
                            Name = "Vladislav",
                            TitleJob = ".NET Developer"
                        },
                        new
                        {
                            Id = new Guid("c86d2102-0a92-4039-be3f-230d15768498"),
                            BirthDate = new DateOnly(2020, 1, 1),
                            MobilePhone = "+1 (111) 111-11-11",
                            Name = "Test",
                            TitleJob = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
